### ISSUE TITLE
Feature Request: An option for how the top element is truncated

### ISSUE THREAD

**Issue by akiomik** [preiter93/tui-widget-list#6]
Thank you for creating this awesome library!

As noted in the comments below, the top item may look a bit strange when the `truncate` option is enabled.

https://github.com/preiter93/tui-widget-list/blob/1fd8f81ee4006852411a22051c70986d05cce451/src/state.rs#L153-L155

If possible, it would be great if you could add an option to control the truncation of the top item.

**Comment by akiomik** [comment]
For reference, I am controlling this by adding a method to `Listable` that tells it that it is an item to be truncated. But, TBH, this is not a smart way.

https://github.com/preiter93/tui-widget-list/compare/main...akiomik:tui-widget-list:truncate-top

**Comment by preiter93** [comment]
Hey, that was something I wanted to look into

I wonder if we can instead render the truncated element in a temporary buffer and then copy the rows from the temporary buffer over into the real buffer 🤔 I think I will take a look at it this weekend

**Comment by preiter93** [comment]
@akiomik can you checkout https://github.com/preiter93/tui-widget-list/pull/7 
if this is what you are looking for?

**Comment by akiomik** [comment]
Brilliant! It worked perfectly in the social client I am developing 💯 

<img width="832" alt="スクリーンショット 2024-01-12 10 24 06" src="https://github.com/preiter93/tui-widget-list/assets/1457682/9ac39735-05d2-42e7-aa97-6fb0fd2eda9b">

**Comment by preiter93** [comment]
great! The fix is published in 0.6.1

**Comment by akiomik** [comment]
Thank you for your kind cooperation😸
